# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('madiadiem', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tendiadiem', models.CharField(max_length=50)),
                ('mota', models.CharField(max_length=100)),
                ('imgpath', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('mahoadon', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ngaylaphoadon', models.DateField()),
                ('giatrihoadon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('mahopdong', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ngayki', models.DateField()),
                ('ngayhethang', models.DateField()),
                ('giatrihopdong', models.FloatField()),
                ('noidunghopdong', models.CharField(max_length=200)),
                ('trangthaihopdong', models.CharField(max_length=50)),
                ('makhachhang', models.CharField(max_length=5)),
                ('maloaihopdong', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makhachhang', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenkhachhang', models.CharField(max_length=50)),
                ('cmnd', models.PositiveIntegerField()),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.BooleanField()),
                ('diachi', models.CharField(max_length=50)),
                ('sodienthoai', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongvedat', models.PositiveIntegerField()),
                ('thanhtien', models.FloatField()),
                ('makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.KhachHang')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiTour',
            fields=[
                ('maloaitour', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenloaitour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiTour_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giave', models.FloatField()),
                ('loaitour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.LoaiTour')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('manhanvien', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tennhanvien', models.CharField(max_length=50)),
                ('cmnd', models.PositiveIntegerField()),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.BooleanField()),
                ('diachi', models.CharField(max_length=50)),
                ('sodienthoai', models.PositiveIntegerField()),
                ('chucvu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('maphongban', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenphongban', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhuLucKhachHang',
            fields=[
                ('maphuluckhachhang', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenphuluckhachhang', models.CharField(max_length=50)),
                ('cmnd', models.PositiveIntegerField()),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.BooleanField()),
                ('sodienthoai', models.PositiveIntegerField()),
                ('makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.KhachHang')),
            ],
        ),
        migrations.CreateModel(
            name='PhuongTienDiChuyen',
            fields=[
                ('maphuongtien', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenphuongtien', models.CharField(max_length=50)),
                ('socho', models.PositiveIntegerField()),
                ('loaiphuongtien', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('mataikhoan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tentaikhoan', models.CharField(max_length=50)),
                ('matkhau', models.CharField(max_length=50)),
                ('manhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.NhanVien')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('matour', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tentour', models.CharField(max_length=50)),
                ('ngaybatdau', models.DateTimeField()),
                ('ngayketthuc', models.DateTimeField()),
                ('trangthaitour', models.CharField(max_length=50)),
                ('madiadiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madiadiemden', to='webapp.DiaDiem')),
            ],
        ),
        migrations.AddField(
            model_name='phuongtiendichuyen',
            name='matour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='maphongban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.PhongBan'),
        ),
        migrations.AddField(
            model_name='loaitour_tour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='loaitour',
            name='tour',
            field=models.ManyToManyField(through='webapp.LoaiTour_Tour', to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='khachhang_tour',
            name='matour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='tour',
            field=models.ManyToManyField(through='webapp.KhachHang_Tour', to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='manhanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manhanvienlaphopdong', to='webapp.NhanVien'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='matour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tour'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='mahopdong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.HopDong'),
        ),
    ]
